package com.aurafx.sdk.api

enum class GiftFxCategory {
    Temporal,
    Portal,
    Creature,
    Hologram,
    Paint,
    Shadow,
    World,
    Gravity,
    Dimension,
    Ink,
    Fantasy,
    SciFi,
    Nature,
    Cinematic,
    Adventure,
    Cosmic,
    Magic,
    Tech,
    Premium,
}

enum class GiftFxRendererType {
    TimeFreeze,
    PortalDoor,
    MeteorCreature,
    HologramClone,
    MagicPaint,
    GiantShadow,
    MiniWorld,
    GravityFlip,
    MirrorDimension,
    InkUniverse,
    NeonTrain,
    FloatingCastle,
    DragonFlight,
    OceanWave,
    Volcano,
    SakuraWorld,
    SamuraiPortal,
    RobotArrival,
    SpaceStation,
    BlackHole,
    CrystalForest,
    MoonEclipse,
    CloudCity,
    ThunderGod,
    AuroraDance,
    LavaRift,
    FairyGarden,
    SteamMachine,
    PaperUniverse,
    MagneticField,
    LaserShow,
    DigitalRain,
    PixelWorld,
    UnderwaterRealm,
    DesertStorm,
    IcePalace,
    FlowerBloom,
    JungleEscape,
    PhantomTrain,
    ClockworkDimension,
    RocketLaunch,
    MeteorShower,
    LevitatingTemple,
    StormEye,
    FloatingIslands,
    AlienContact,
    GoldenDimension,
    MusicDimension,
    CosmicButterfly,
    FinalDimension,
}

enum class GiftFxLayer {
    Background,
    BehindSubject,
    SubjectAttached,
    Foreground,
    FullFrame,
}

enum class GiftFxAnchor {
    ScreenCenter,
    Face,
    Head,
    Body,
    Shoulder,
    Eyes,
    Torso,
}

enum class GiftFxOcclusion {
    None,
    PersonMask,
    HairMask,
    PersonAndHair,
}

enum class GiftFxTrackingNeed {
    None,
    Face,
    Body,
    FaceOrBody,
    Segmentation,
}

enum class GiftFxCleanupBehavior {
    AutoFade,
    ParticleCollapse,
    SnapRelease,
}
